
version: 2.1

jobs:
  build:
    docker:
      - image: haskell:8.8.3
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          key: haskell-dependencies-{{ checksum "circleci-cabal.cabal" }}
      - run:
          name: Update Dependencies
          command: cabal new-update && cabal new-install --lib
      - run:
          name: Haskell - Compile
          command: cabal new-build
      - run:
          name: Haskell - Compile Tests
          command: cabal new-build --enable-tests
      - save_cache:
          name: Haskell - Cache Dependencies
          key: haskell-dependencies-{{ checksum "circleci-cabal.cabal" }}
          paths:
            - "/root/.cabal"
            - "dist-newstyle" 